import pw from '/Users/pigr/Developer/fe-forum-event-web/node_modules/@playwright/test/index.js';
const { chromium, devices } = pw;
const b = await chromium.launch();
const page = await (await b.newContext({ ...devices['iPhone 13'] })).newPage();
const errs=[]; page.on('pageerror',e=>errs.push(e.message));
page.on('console',m=>{ if(m.type()==='error') errs.push(m.text()); });
const ok=(c,m)=>console.log((c?'OK   ':'ROTTO')+'  '+m);
await page.goto('http://localhost:8899/',{waitUntil:'networkidle'});
await page.locator('#tabLog').click(); await page.waitForTimeout(700);
const txt = await page.locator('.wrap').innerText();
const h = await page.locator('h3.sec').first().textContent();
ok(/ne restano 9/.test(h), `il titolo conta quelle che restano: "${h}"`);
const spuntate = await page.locator('.row.done').count();
ok(spuntate === 4, `righe con la spunta: ${spuntate} — voce fatta, Pechino, Xi'an, treno del 10`);
const daf = await page.locator('.rows').first().innerText();
ok(daf.includes('fatto'), 'la voce comprata dice "fatto" al posto della scadenza');
const prima = await page.locator('.rows').first().locator('.row').first().innerText();
ok(!/^26 ago$/m.test(prima), 'la colonna della scadenza non mostra piu 26 ago');
const hot = await page.locator('.row.hot').count();
ok(hot === 2, `voci ancora urgenti: ${hot} (erano 3)`);
console.log('\nerrori:', errs.length?errs:'nessuno');
await page.screenshot({path:'shots/09-logistica.png', fullPage:false});
await b.close();
